@table = tag
@id = 1

// Nous allons ajouter les tags correspondant à un article dans ArticleDetailScreen
// Il s'agit d’une relation ManyToMany, la correspondance entre les tags et les articles
// se fait dans une table intermédiaire : article_tag

@body = {"title":"titre de la nouvelle ligne", "is_deleted": 0}

# @body = {"with": ["account", "role", {"article":"article_tag"}, "comment", "theme", "appuser", {"tag":"article_tag"}]}

GET http://blog-api.loc/tag

###
GET http://blog-api.loc/tagDetail/{{id}}

###
POST http://blog-api.loc/{{table}}
Content-Type: application/json
// Il faut préciser qu’on envoi du json avec Content-Type: application/json, 
// et ajouter la variable body qui contient les valeur à insérer ou mettre à jour en DB

{{body}}

###
PUT http://blog-api.loc/{{table}}/{{id}}
Content-Type: application/json

{{body}}

###
PATCH http://blog-api.loc/tag/{{id}}

###
DELETE http://blog-api.loc/tag/{{id}}
